baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #XXX'

[[module.imports]]
path = "github.com/markdumay/hugo-mod-issue-config"

[[module.imports.mounts]]
source = "layouts"
target = "layouts"

[[module.imports]]
path = "github.com/markdumay/hugo-mod-issue-hugo"

[[module.imports.mounts]]
source = "layouts"
target = "layouts"
